language: erlang
otp_release:
  - 20.3.8.9

dist: xenial

before:
  - kerl list installations

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libzmq3-dev

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update          ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install zeromq  ; fi
 
script:
  - rebar3 do compile, eunit
